<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2018sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:ske:fastsetting:skatteinfo:saldoRente:v3" exclude-result-prefixes="xs ns0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<melding xmlns="urn:ske:fastsetting:formueinntekt:skattemelding:v6.2">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">urn:ske:fastsetting:formueinntekt:skattemelding:v6.2 file:///.//src//main//resources//</xsl:attribute>
			<xsl:for-each select="/oppgave/oppgavegiver/partsnummer">
				<xsl:variable name="var2_cur" select="."/>
				<partsreferanse>
					<xsl:value-of select="."/>
				</partsreferanse>
			</xsl:for-each>
			<inntektsaar>
				<xsl:value-of select="'2017'"/>
			</inntektsaar>
			<bankOgLaan>
				<bank>
					<xsl:for-each select="oppgave">
						<xsl:variable name="var3_cur" select="."/>
						<konto>
							<bankensNavn>
								<tekst>
									<tekst>
										<xsl:value-of select="oppgavegiver/organisasjonsnavn"/>
									</tekst>
								</tekst>
								<spraak>
									<xsl:for-each select="oppgavegiver/internasjonalIdentifikator">
										<xsl:variable name="var4_cur" select="."/>
										<spraak>
											<xsl:value-of select="utstedtAvLand"/>
										</spraak>
									</xsl:for-each>
								</spraak>
							</bankensNavn>
							<organisasjonsnummer>
								<organisasjonsnummer>
									<xsl:value-of select="oppgavegiver/organisasjonsnummer"/>
								</organisasjonsnummer>
							</organisasjonsnummer>
							<kontonummer>
								<tekst>
									<xsl:value-of select="kontonummer"/>
								</tekst>
							</kontonummer>
							<kontoeier>
								<xsl:for-each select="oppgaveeier/organisasjonsnavn">
									<xsl:variable name="var5_cur" select="."/>
									<navn>
										<xsl:value-of select="."/>
									</navn>
								</xsl:for-each>
							</kontoeier>
							<innskudd>
								<beloep>
									<beloepINok>
										<xsl:for-each select="innskudd">
											<xsl:variable name="var6_cur" select="."/>
											<beloepSomHeltall>
												<xsl:value-of select="number(.)"/>
											</beloepSomHeltall>
										</xsl:for-each>
									</beloepINok>
								</beloep>
							</innskudd>
							<gjeld>
								<beloep>
									<beloepINok>
										<xsl:for-each select="utlaan">
											<xsl:variable name="var7_cur" select="."/>
											<beloepSomHeltall>
												<xsl:value-of select="number(.)"/>
											</beloepSomHeltall>
										</xsl:for-each>
									</beloepINok>
								</beloep>
							</gjeld>
							<xsl:for-each select="renter/paaloepteRenter">
								<xsl:variable name="var8_cur" select="."/>
								<paaloepteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:value-of select="number(.)"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</paaloepteRenter>
							</xsl:for-each>
							<xsl:for-each select="renter/opptjenteRenter">
								<xsl:variable name="var9_cur" select="."/>
								<opptjenteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:value-of select="number(.)"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</opptjenteRenter>
							</xsl:for-each>
							<xsl:for-each select="renter/betalteMisligholdteRenter">
								<xsl:variable name="var10_cur" select="."/>
								<betalteMisligholdteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:value-of select="number(.)"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</betalteMisligholdteRenter>
							</xsl:for-each>
						</konto>
					</xsl:for-each>
				</bank>
			</bankOgLaan>
		</melding>
	</xsl:template>
</xsl:stylesheet>
