<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2018sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="urn:ske:fastsetting:skatteinfo:saldoRente:v3" exclude-result-prefixes="xs fn ns0">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var3_oppgave" as="node()?" select="ns0:oppgave"/>
		<melding xmlns="urn:ske:fastsetting:formueinntekt:skattemelding:v6.2">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" select="'urn:ske:fastsetting:formueinntekt:skattemelding:v6.2 file:///C:/Users/x0xoyr/Documents/XSD/Skattemelding%20ver.%206.2.xsd'"/>
			<xsl:for-each select="$var3_oppgave/ns0:oppgavegiver/ns0:partsnummer">
				<partsreferanse>
					<xsl:sequence select="fn:string(.)"/>
				</partsreferanse>
			</xsl:for-each>
			<inntektsaar>
				<xsl:sequence select="xs:string(xs:gYear('2017'))"/>
			</inntektsaar>
			<bankOgLaan>
				<bank>
					<xsl:for-each select="$var3_oppgave">
						<xsl:variable name="var1_renter" as="node()" select="ns0:renter"/>
						<xsl:variable name="var2_oppgavegiver" as="node()" select="ns0:oppgavegiver"/>
						<konto>
							<bankensNavn>
								<tekst>
									<tekst>
										<xsl:sequence select="fn:string($var2_oppgavegiver/ns0:organisasjonsnavn)"/>
									</tekst>
								</tekst>
								<spraak>
									<xsl:for-each select="$var2_oppgavegiver/ns0:internasjonalIdentifikator">
										<spraak>
											<xsl:sequence select="fn:string(ns0:utstedtAvLand)"/>
										</spraak>
									</xsl:for-each>
								</spraak>
							</bankensNavn>
							<organisasjonsnummer>
								<organisasjonsnummer>
									<xsl:sequence select="fn:string($var2_oppgavegiver/ns0:organisasjonsnummer)"/>
								</organisasjonsnummer>
							</organisasjonsnummer>
							<kontonummer>
								<tekst>
									<xsl:sequence select="fn:string(ns0:kontonummer)"/>
								</tekst>
							</kontonummer>
							<kontoeier>
								<xsl:for-each select="ns0:oppgaveeier/ns0:fornavn">
									<navn>
										<xsl:sequence select="fn:string(.)"/>
									</navn>
								</xsl:for-each>
							</kontoeier>
							<innskudd>
								<beloep>
									<beloepINok>
										<xsl:for-each select="ns0:innskudd">
											<beloepSomHeltall>
												<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
											</beloepSomHeltall>
										</xsl:for-each>
									</beloepINok>
								</beloep>
							</innskudd>
							<gjeld>
								<beloep>
									<beloepINok>
										<xsl:for-each select="ns0:utlaan">
											<beloepSomHeltall>
												<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
											</beloepSomHeltall>
										</xsl:for-each>
									</beloepINok>
								</beloep>
							</gjeld>
							<xsl:for-each select="$var1_renter/ns0:paaloepteRenter">
								<paaloepteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</paaloepteRenter>
							</xsl:for-each>
							<xsl:for-each select="$var1_renter/ns0:opptjenteRenter">
								<opptjenteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</opptjenteRenter>
							</xsl:for-each>
							<xsl:for-each select="$var1_renter/ns0:betalteMisligholdteRenter">
								<betalteMisligholdteRenter>
									<beloep>
										<beloepINok>
											<beloepSomHeltall>
												<xsl:sequence select="xs:string(xs:integer(fn:string(.)))"/>
											</beloepSomHeltall>
										</beloepINok>
									</beloep>
								</betalteMisligholdteRenter>
							</xsl:for-each>
						</konto>
					</xsl:for-each>
				</bank>
			</bankOgLaan>
		</melding>
	</xsl:template>
</xsl:stylesheet>

