<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2018sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:ske:fastsetting:skatteinfo:saldoRente:v3"
                exclude-result-prefixes="xs ns0">
    <xsl:output method="xml" encoding="UTF-8" indent="yes"/>

    <xsl:template match="/">

        <melding xmlns="urn:ske:fastsetting:formueinntekt:skattemelding:v6.2">

            <xsl:for-each select="/oppgave/oppgavegiver/partsnummer">

                <partsreferanse>
                    <xsl:value-of select="."/>
                </partsreferanse>
            </xsl:for-each>
            <inntektsaar>
                <xsl:value-of select="'2017'"/>
            </inntektsaar>


            <bankOgLaan>
                <bank>
                    <konto>
                        <xsl:for-each select="oppgave">
                            <bankensNavn>
                                <tekst>
                                    <tekst>
                                        <xsl:value-of
                                                select="/skatteinfoDokument/data/content/oppgave/oppgavegiver/organisasjonsnavn"/>
                                    </tekst>
                                </tekst>
                            </bankensNavn>
                        </xsl:for-each>
                    </konto>
                </bank>
            </bankOgLaan>

            <bankOgLaan>
                <bank>
                    <konto>
                        <xsl:for-each select="oppgave">
                            <bankensNavn><tekst><tekst>
                                        <xsl:value-of select="/oppgavegiver/organisasjonsnavn"/>
                            </tekst></tekst></bankensNavn>
                            <bankensNavn><tekst><tekst>
                                <xsl:value-of select="/oppgavegiver/organisasjonsnavn"/>
                            </tekst></tekst></bankensNavn>
                        </xsl:for-each>
                    </konto>
                </bank>
            </bankOgLaan>

            /skatteinfoDokument/data/content/oppgave/kontonummer = /skattemelding/bankOgLaan/bank/konto/kontonummer
            /skatteinfoDokument/data/content/oppgave/Innskudd = /skattemelding/bankOgLaan/bank/konto/innskudd/beloep


            <bankOgLaan>
                <bank>
                    <xsl:for-each select="oppgave">
                        <konto>
                            <bankensNavn>
                                <tekst>
                                    <tekst>
                                        <xsl:value-of select="oppgavegiver/organisasjonsnavn"/>
                                    </tekst>
                                </tekst>
                            </bankensNavn>
                            <organisasjonsnummer>
                                <organisasjonsnummer>
                                    <xsl:value-of select="oppgavegiver/organisasjonsnummer"/>
                                </organisasjonsnummer>
                            </organisasjonsnummer>
                            <kontonummer>
                                <tekst>
                                    <xsl:value-of select="kontonummer"/>
                                </tekst>
                            </kontonummer>
                            <kontoeier>
                                <xsl:for-each select="oppgaveeier/organisasjonsnavn">
                                    <navn>
                                        <xsl:value-of select="."/>
                                    </navn>
                                </xsl:for-each>
                            </kontoeier>
                            <innskudd>
                                <beloep>
                                    <beloepINok>
                                        <xsl:for-each select="innskudd">
                                            <beloepSomHeltall>
                                                <xsl:value-of select="number(.)"/>
                                            </beloepSomHeltall>
                                        </xsl:for-each>
                                    </beloepINok>
                                </beloep>
                            </innskudd>
                            <gjeld>
                                <beloep>
                                    <beloepINok>
                                        <xsl:for-each select="utlaan">
                                            <beloepSomHeltall>
                                                <xsl:value-of select="number(.)"/>
                                            </beloepSomHeltall>
                                        </xsl:for-each>
                                    </beloepINok>
                                </beloep>
                            </gjeld>
                            <xsl:for-each select="renter/paaloepteRenter">
                                <paaloepteRenter>
                                    <beloep>
                                        <beloepINok>
                                            <beloepSomHeltall>
                                                <xsl:value-of select="number(.)"/>
                                            </beloepSomHeltall>
                                        </beloepINok>
                                    </beloep>
                                </paaloepteRenter>
                            </xsl:for-each>
                            <xsl:for-each select="renter/opptjenteRenter">
                                <opptjenteRenter>
                                    <beloep>
                                        <beloepINok>
                                            <beloepSomHeltall>
                                                <xsl:value-of select="number(.)"/>
                                            </beloepSomHeltall>
                                        </beloepINok>
                                    </beloep>
                                </opptjenteRenter>
                            </xsl:for-each>
                            <xsl:for-each select="renter/betalteMisligholdteRenter">
                                <betalteMisligholdteRenter>
                                    <beloep>
                                        <beloepINok>
                                            <beloepSomHeltall>
                                                <xsl:value-of select="number(.)"/>
                                            </beloepSomHeltall>
                                        </beloepINok>
                                    </beloep>
                                </betalteMisligholdteRenter>
                            </xsl:for-each>
                        </konto>
                    </xsl:for-each>
                </bank>
            </bankOgLaan>
        </melding>
    </xsl:template>
</xsl:stylesheet>
